### ISSUE TITLE
Invalid ST code format

### ISSUE THREAD

**Issue by ssincxv** [ShinobiCat/bliz_totp#1]
![image](https://github.com/user-attachments/assets/26214787-613c-418c-8ac6-07771ab3c0a3)

**Comment by ssincxv** [comment]
Can you tell me how to fix it?

**Comment by digikwal** [comment]
> Can you tell me how to fix it?

Hi @ssincxv ,

I've updated the script to allow for a more flexible character pattern in the ST code validation. Additionally, you will now have an option to continue even if the ST code format is invalid.

Please pull the latest version of the script and re-run the .py file.

Also, don't forget to refresh your login page — the ST code might have changed since the last time you checked.

Good luck!
